// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPqwUzKodTT1npiMJzkMQBV6uutsayWo4',
    appId: '1:524107650640:android:fdf322e6c19813f2b3e355',
    messagingSenderId: '524107650640',
    projectId: 'aksara-78d63',
    storageBucket: 'aksara-78d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVRq-2A5uBKkETf-6-o3m3-hhwAEJU_C8',
    appId: '1:524107650640:ios:75909b52313c53b8b3e355',
    messagingSenderId: '524107650640',
    projectId: 'aksara-78d63',
    storageBucket: 'aksara-78d63.appspot.com',
    androidClientId: '524107650640-fdhpea7evtntp360rbuocb0m9v3s7916.apps.googleusercontent.com',
    iosClientId: '524107650640-7vrk0p63tb5iusflnkrpfkj05toah7p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.aksara',
  );
}
